Entity/MenuItems.php
<?php

namespace CMS\MenuBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * MenuItems
 */
class MenuItems
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var integer
     */
    private $menu_type;

    /**
     * @var integer
     */
    private $parent;

    /**
     * @var ArrayCollection
     */
    private $childs;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $alias;

    /**
     * @var string
     */
    private $url;

    /**
     * @var ArrayCollection
     */
    private $roles;

    /**
     * @var int
     */
    private $sort = 0;

    /**
     * @var string
     */
    private $css_classes;

    /**
     * @var boolean
     */
    private $is_published;

    /**
     * @var boolean
     */
    private $is_deleted;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    public function __construct()
    {
        $this->childs = new ArrayCollection();
        $this->roles = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getMenuType()
    {
        return $this->menu_type;
    }

    /**
     * @param mixed $menu_type
     * @return $this
     */
    public function setMenuType($menu_type)
    {
        $this->menu_type = $menu_type;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param mixed $parent
     * @return $this
     */
    public function setParent($parent)
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getChilds()
    {
        return $this->childs;
    }

    /**
     * @param ArrayCollection $childs
     * @return $this
     */
    public function setChilds($childs)
    {
        $this->childs = $childs;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param string $url
     * @return MenuItems
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param ArrayCollection $roles
     * @return MenuItems
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return int
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * @param int $sort
     * @return MenuItems
     */
    public function setSort($sort)
    {
        $this->sort = $sort;

        return $this;
    }

    /**
     * @return string
     */
    public function getCssClasses()
    {
        return $this->css_classes;
    }

    /**
     * @param string $css_classes
     *
     * @return MenuItems
     */
    public function setCssClasses($css_classes)
    {
        $this->css_classes = $css_classes;

        return $this;
    }

    /**
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * @param string $alias
     * @return MenuItems
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * @param boolean $is_published
     * @return $this
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param boolean $is_deleted
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return $this
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return $this
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return $this
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return $this
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;
        return $this;
    }


}

Form/MenuTypesType.php
<?php

namespace CMS\MenuBundle\Form;

use CMS\LocalizationBundle\Form\Types\LocaleTextareaType;
use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MenuTypesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', LocaleTextType::class)
            ->add('alias')
            ->add('description', LocaleTextareaType::class, array(
                'required' => false
            ))
            ->add('sort')
            ->add('is_published')
            ->add('is_deleted');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\MenuBundle\Entity\MenuTypes',
            'translation_domain' => 'systems'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'cms_menubundle_menutypes';
    }
}

Controller/MenuTypesController.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel
 * Date: 12.01.15
 * Time: 17:03
 */

namespace CMS\MenuBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class MenuTypesController extends Controller
{
    public function listAction()
    {
        $service = $this->get('cms.menu.types.service');

        return $this->render('MenuBundle:MenuTypes:list.html.twig', array(
            'types' => $service->findAll()
        ));
    }

    public function createAction(Request $request)
    {
        $service = $this->get('cms.menu.types.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();

                $service->create($data);

                return $this->redirect($this->generateUrl('cms_menu_types_list'));
            }
        }

        return $this->render('MenuBundle:MenuTypes:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.menu.types.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();

                $service->create($data);

                return $this->redirect($this->generateUrl('cms_menu_types_list'));
            }
        }

        return $this->render('MenuBundle:MenuTypes:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function deleteAction($id)
    {
        $service = $this->get('cms.menu.types.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_menu_types_list'));
    }
}

Resources/views/MenuTypes/edit.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@localization_tabs_js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block body %}
    {% embed 'MenuBundle::main.html.twig' %}
        {% block main %}
            <div class="row">
                {% form_theme form 'MenuBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    {{ form_start(form, {'method': 'POST', 'attr': {'class': 'form-horizontal'}}) }}
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                'label': 'Title'|trans({},'messages'),
                                }) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/MenuTypes/list.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block body %}
    {% embed 'MenuBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_menu_types_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans({}, 'systems') }}</th>
                    <th>{{ 'Alias'|trans({}, 'systems') }}</th>
                    <th>{{ 'Date'|trans({}, 'systems') }}</th>
                    <th>{{ 'Sort'|trans({}, 'systems') }}</th>
                    <th>{{ 'Is published'|trans({}, 'systems') }}</th>
                    <th>{{ 'Description'|trans({}, 'systems') }}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for type in types %}
                        <tr>
                            <td><input type="checkbox" value="{{ type.id }}" name="mark[]"/></td>
                            <td>{{ type.id }}</td>
                            <td>
                                <a href="{{ url('cms_menu_types_edit', {id: type.id}) }}">
                                    {{ type.title|locale }}
                                </a>
                            </td>
                            <td>{{ type.alias }}</td>
                            <td>{{ type.dateCreate|date('d.m.Y') }}</td>
                            <td>{{ type.sort }}</td>
                            <td>{{ type.isPublished }}</td>
                            <td>{{ type.description|locale }}</td>
                            <td><a href='{{ url('cms_menu_types_edit', {id: type.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_menu_types_delete', {id: type.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}